all: array_treversing

array_treversing: array_treversing.o
	$(g++) -o array_treversing array_treversing.o

array_treversing.o: array_treversing.cpp
	$(g++) -c array_treversing.cpp

clean:
	rm -rf *.o array_treversing